<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Textmate bundle for Elixir Programming Language.</string>
	<key>fileTypes</key>
	<array>
		<string>ex</string>
		<string>exs</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!/.*\belixir</string>
	<key>foldingStartMarker</key>
	<string>(after|else|catch|rescue|\-\&gt;|\{|\[|do)\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*((\}|\]|after|else|catch|rescue)\s*$|end\b)</string>
	<key>injections</key>
	<dict>
		<key>L:(meta.embedded.block.heex meta.tag - meta.embedded.line.heex - string.quoted.double.html - string.quoted.single.html)</key>
		<dict>
			<key>comment</key>
			<string>{expressions} and :if/:for in HTML tags of ~H templates.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.heex#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.heex#special_attributes</string>
				</dict>
			</array>
		</dict>
		<key>R:meta.embedded.block.eex meta.tag meta.attribute string.quoted</key>
		<dict>
			<key>comment</key>
			<string>EEx tags in attribute values of ~L and ~E templates.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.elixir</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~E</string>
	<key>name</key>
	<string>Elixir</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.elixir</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.method.elixir</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.elixir</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([A-Z]\w*)\s*(\.)\s*([a-z_]\w*[!?]?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.symbol.elixir</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.method.elixir</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.elixir</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\:\w+)\s*(\.)\s*([_]?\w*[!?]?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.pipe.elixir</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.elixir</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\|\&gt;)\s*([a-z_]\w*[!?]?)</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#core_syntax</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>core_syntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(defmodule)\b(?![?!:])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(do)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.module.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[A-Z]\w*(?:\.[A-Z]\w*)*\b</string>
							<key>name</key>
							<string>entity.name.type.module.elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(defprotocol)\b(?![?!:])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.protocol.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(do)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.protocol.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.protocol_declaration.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[A-Z]\w*(?:\.[A-Z]\w*)*\b</string>
							<key>name</key>
							<string>entity.name.type.protocol.elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(defimpl)\b(?![?!:])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.protocol.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\b(do)\b</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.protocol.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.protocol_implementation.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b[A-Z]\w*(?:\.[A-Z]\w*)*\b</string>
							<key>name</key>
							<string>entity.name.type.protocol.elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(def|defn|defmacro|defdelegate|defguard)\s+([a-zA-Z_]\w*[?!]?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.public.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>A head without do or do: (a body-less clause, defdelegate) ends at the end of the line.</string>
					<key>end</key>
					<string>(\bdo:)|(\bdo\b)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.keywords.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.public.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function_parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(defp|defnp|defmacrop|defguardp)\s+([a-zA-Z_]\w*[?!]?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.private.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>A head without do or do: (a body-less clause, defdelegate) ends at the end of the line.</string>
					<key>end</key>
					<string>(\bdo:)|(\bdo\b)|$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.keywords.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.module.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.private.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function_parameters</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~H|~LVN)(\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.heex</string>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.heex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~H|~LVN)([\"'|/])(?=(?:(?!\1)[^\\])*\1)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.heex</string>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.heex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~H|~LVN)\((?=[^\)\\]*\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.heex</string>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.heex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~H|~LVN)\[(?=[^\]\\]*\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.heex</string>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.heex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~H|~LVN)\{(?=[^\}\\]*\})</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.heex</string>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.heex</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~L|~E)(\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.elixir</string>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.eex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~L|~E)([\"'|/])(?=(?:(?!\1)[^\\])*\1)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.elixir</string>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.eex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~L|~E)\((?=[^\)\\]*\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.elixir</string>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.eex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~L|~E)\[(?=[^\]\\]*\])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.elixir</string>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.eex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?:~L|~E)\{(?=[^\}\\]*\})</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>text.html.elixir</string>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.eex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( {2})(?=@)((@)(?:module|type|short)?doc)\s+((?:~[a-z])?(\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown_2</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( {2})(?=@)((@)(?:module|type|short)?doc)\s+(~[A-Z](\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown_2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( {4})(?=@)((@)(?:module|type|short)?doc)\s+((?:~[a-z])?(\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown_4</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^( {4})(?=@)((@)(?:module|type|short)?doc)\s+(~[A-Z](\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown_4</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>()((@)(?:module|type|short)?doc)\s+((?:~[a-z])?(\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>()((@)(?:module|type|short)?doc)\s+(~[A-Z](\"\"\"|'''))</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*(\5)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.heredoc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>((@)(?:module|type|short)?doc)\s+false\b</string>
					<key>name</key>
					<string>comment.block.documentation.false</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>((@)(?:module|type|short)?doc)\s+((?:~[a-z])?")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((@)(?:module|type|short)?doc)\s+(~[A-Z]")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.documentation.string</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.attr.doc.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>@doc with metadata, e.g. @doc since: "1.0.0"</string>
					<key>match</key>
					<string>((@)(?:module|type|short)?doc)\b(?![?!])</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\.)\b(do|end|case|for|if|cond|unless|try|receive|fn|defmodule|defp?|defprotocol|defimpl|defstruct|defnp?|defmacrop?|defguardp?|defdelegate|defexception|defoverridable|exit|after|rescue|catch|else|raise|reraise|throw|import|require|alias|use|quote|unquote|unquote_splicing|super|with)\b(?![?!:])</string>
					<key>name</key>
					<string>keyword.control.elixir</string>
				</dict>
				<dict>
					<key>comment</key>
					<string> as above, just doesn't need a 'end' and does a logic operation</string>
					<key>match</key>
					<string>(?&lt;!\.)\b(and|not|or|when|in)\b(?![?!:])</string>
					<key>name</key>
					<string>keyword.operator.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[a-z_]\w*[!?]?(?=\s*\.?\s*\()</string>
					<key>name</key>
					<string>entity.name.function.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Z]\w*\b</string>
					<key>name</key>
					<string>entity.name.type.class.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(nil|true|false)\b(?![?!])</string>
					<key>name</key>
					<string>constant.language.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(__(CALLER|ENV|MODULE|DIR|STACKTRACE)__)\b(?![?!])</string>
					<key>name</key>
					<string>variable.language.elixir</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*)((@)(?:spec|callback|macrocallback))(?![?!\w])\s*(?:(?!unquote\b)([a-z_]\w*[?!]?)(?=\s*(?:\(|::(?!:)|$)))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.type.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.spec.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Continues on lines indented deeper than the attribute, as in formatted specs and unions.</string>
					<key>name</key>
					<string>meta.type.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typespec</string>
						</dict>
					</array>
					<key>while</key>
					<string>^\1\s+(?=\S)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*)((@)(?:typep?|opaque))(?![?!\w])\s*(?:(?!unquote\b)([a-z_]\w*[?!]?)(?=\s*(?:\(|::(?!:)|$)))?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.type.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Continues on lines indented deeper than the attribute, as in formatted specs and unions.</string>
					<key>name</key>
					<string>meta.type.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typespec</string>
						</dict>
					</array>
					<key>while</key>
					<string>^\1\s+(?=\S)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.keyword.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@)(?:spec|callback|macrocallback|typep?|opaque)\b(?![?!])</string>
					<key>name</key>
					<string>keyword.declaration.type.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attribute.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Attributes with a meaning to the compiler, Mix, or ExUnit.</string>
					<key>match</key>
					<string>(@)(?:impl|deprecated|(?:before_|after_)?compile|after_verify|behaviou?r|enforce_keys|fallback_to_any|optional_callbacks|file|dialyzer|derive|external_resource|vsn|on_definition|on_load|nifs|moduletag|describetag|tag)\b(?![?!])</string>
					<key>name</key>
					<string>support.attr.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@)[a-zA-Z_]\w*</string>
					<key>name</key>
					<string>variable.other.readwrite.module.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&amp;)\d+</string>
					<key>name</key>
					<string>variable.other.anonymous.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;(?![&amp;])</string>
					<key>name</key>
					<string>variable.other.anonymous.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\^)[a-z_]\w*</string>
					<key>name</key>
					<string>variable.other.capture.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0x[0-9A-Fa-f](?&gt;_?[0-9A-Fa-f])*\b</string>
					<key>name</key>
					<string>constant.numeric.hex.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d(?&gt;_?\d)*(\.(?![^[:space:][:digit:]])(?&gt;_?\d)+)([eE][-+]?\d(?&gt;_?\d)*)?\b</string>
					<key>name</key>
					<string>constant.numeric.float.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d(?&gt;_?\d)*\b</string>
					<key>name</key>
					<string>constant.numeric.integer.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0b[01](?&gt;_?[01])*\b</string>
					<key>name</key>
					<string>constant.numeric.binary.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0o[0-7](?&gt;_?[0-7])*\b</string>
					<key>name</key>
					<string>constant.numeric.octal.elixir</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:'</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>constant.other.symbol.single-quoted.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>:"</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>constant.other.symbol.double-quoted.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"(?=(?:[^"\\]|\\.)*":(?!:))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")(:)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.other.keywords.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'(?=(?:[^'\\]|\\.)*':(?!:))</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')(:)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.other.keywords.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&gt;''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Single-quoted heredocs</string>
					<key>end</key>
					<string>^\s*'''</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.heredoc.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single quoted string (allows for interpolation)</string>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&gt;""")</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Double-quoted heredocs</string>
					<key>end</key>
					<string>^\s*"""</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.heredoc.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>double quoted string (allows for interpolation)</string>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r(\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.heredoc.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r([/|\"'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~r&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R(\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.heredoc.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R([/|\"'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~R&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.regexp.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z](\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.heredoc.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z]([/|\"'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z]\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z]\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z]\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[a-z]&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolated_elixir</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#escaped_char</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*(\"\"\"|''')</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.heredoc.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*([/|\"'])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\1[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\][a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>~[A-Z][A-Z0-9]*&lt;</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;[a-zA-Z0-9]*</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.elixir</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.sigil.literal.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>An escaped terminator does not end the sigil.</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>symbols</string>
					<key>match</key>
					<string>(?&lt;!:)(:)(?&gt;[a-zA-Z_][\w@]*(?&gt;[?!])?|&lt;~&gt;|&lt;&lt;~|~&gt;&gt;|&lt;~|~&gt;|&lt;\|&gt;|\+\+\+|---|\&lt;\&gt;|===?|!==?|&lt;&lt;&gt;&gt;|&lt;&lt;&lt;|&gt;&gt;&gt;|~~~|::|&lt;\-|\|&gt;|=&gt;|=~|=|/|\\\\|\*\*?|\.\.//|\.\.?\.?|&gt;=?|&lt;=?|&amp;&amp;?&amp;?|\+\+?|\-\-?|\|\|?\|?|\!|@|\%?\{\}|%|\[\]|\^(\^\^)?)</string>
					<key>name</key>
					<string>constant.other.symbol.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>symbols</string>
					<key>match</key>
					<string>(?&gt;[a-zA-Z_][\w@]*(?&gt;[?!])?)(:)(?!:)</string>
					<key>name</key>
					<string>constant.other.keywords.elixir</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=##)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>##</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.elixir</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.section.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!#)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.elixir</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.elixir</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\b_(?!_)\w+[?!]?</string>
					<key>name</key>
					<string>comment.unused.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b_\b</string>
					<key>name</key>
					<string>comment.wildcard.elixir</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>
			matches questionmark-letters.

			examples (1st alternation = hex):
			?\x1     ?\x61

			examples (2rd alternation = escaped):
			?\n      ?\b

			examples (3rd alternation = normal):
			?a       ?A       ?0
			?*       ?"       ?(
			?.       ?#

			the negative lookbehind prevents against matching
			p(42.tainted?)
			</string>
					<key>match</key>
					<string>(?&lt;!\w)\?(\\.|[^\s\\])</string>
					<key>name</key>
					<string>constant.numeric.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.elixir</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.custom.elixir</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.elixir</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.range.elixir</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.type.elixir</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.elixir</string>
						</dict>
						<key>15</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.other.elixir</string>
						</dict>
						<key>16</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logical.elixir</string>
						</dict>
						<key>17</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.elixir</string>
						</dict>
						<key>18</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arithmetic.elixir</string>
						</dict>
						<key>19</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.other.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.elixir</string>
						</dict>
						<key>20</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.assignment.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bitwise.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.custom.elixir</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.pipe.elixir</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.arrow.elixir</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.default.elixir</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.concatenation.elixir</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.comparison.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Operators, longest first.</string>
					<key>match</key>
					<string>(\+\+\+|---)|(===|!==)|(\|\|\||&amp;&amp;&amp;|\^\^\^|&lt;&lt;&lt;|&gt;&gt;&gt;|~~~)|(&lt;~&gt;|&lt;&lt;~|~&gt;&gt;|&lt;\|&gt;)|(\|&gt;)|(-&gt;|&lt;-|=&gt;)|(\\\\)|(&lt;&gt;|\+\+|--)|(==|!=|&lt;=|&gt;=|=~)|(&lt;~|~&gt;)|(&amp;&amp;|\|\|)|(\.\.|//)|(::)|(\*\*)|(&lt;&lt;|&gt;&gt;)|((?&lt;!\w)!+)|(&lt;|&gt;)|(\*|\+|-|/)|(\|)|(=)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.separator.other.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\;</string>
					<key>name</key>
					<string>punctuation.separator.statement.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.object.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.separator.method.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{|\}</string>
					<key>name</key>
					<string>punctuation.section.scope.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[|\]</string>
					<key>name</key>
					<string>punctuation.section.array.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(|\)</string>
					<key>name</key>
					<string>punctuation.section.function.elixir</string>
				</dict>
			</array>
		</dict>
		<key>doc_markdown</key>
		<dict>
			<key>comment</key>
			<string>The Markdown used in docs, including doctests and fenced code, which are Elixir.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doctest</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*)(```|~~~)\s*(?:elixir|ex|exs|iex)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.markdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.elixir</string>
					<key>end</key>
					<string>^\s*\2\s*$|(?=^\s*(?:\"\"\"|''')\s*$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.elixir</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\s*)(```|~~~)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^\s*\2\s*$|(?=^\s*(?:\"\"\"|''')\s*$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.raw.block.markdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(#{1,6})\s+.*$</string>
					<key>name</key>
					<string>markup.heading.markdown</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(&gt;)(?!&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quote.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>markup.quote.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doc_markdown_inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list_item.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*([*+-]|\d+\.)(?=\s)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_markdown_inline</string>
				</dict>
			</array>
		</dict>
		<key>doc_markdown_2</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^ {6}(?= *\S)</string>
					<key>comment</key>
					<string>An indented code block; blank lines continue it.</string>
					<key>name</key>
					<string>markup.raw.block.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doctest</string>
						</dict>
					</array>
					<key>while</key>
					<string>^(?: {6}| *$)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_markdown</string>
				</dict>
			</array>
		</dict>
		<key>doc_markdown_4</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^ {8}(?= *\S)</string>
					<key>comment</key>
					<string>An indented code block; blank lines continue it.</string>
					<key>name</key>
					<string>markup.raw.block.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#doctest</string>
						</dict>
					</array>
					<key>while</key>
					<string>^(?: {8}| *$)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doc_markdown</string>
				</dict>
			</array>
		</dict>
		<key>doc_markdown_inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(``)(.+?)(``)|(`)([^`]+)(`)</string>
					<key>name</key>
					<string>markup.raw.inline.markdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.markdown</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Only **bold**: __name__ is far more often an Elixir name like __MODULE__.</string>
					<key>match</key>
					<string>(?&lt;!\w)(\*\*)(?=\S)(.+?)(?&lt;=\S)(\*\*)(?!\w)</string>
					<key>name</key>
					<string>markup.bold.markdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;![\w*])(\*|_)(?=[^\s*_])(.+?)(?&lt;=[^\s*_])(\1)(?![\w*])</string>
					<key>name</key>
					<string>markup.italic.markdown</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)([^\]]+)(\])(\()([^)\s]+)(\))</string>
					<key>name</key>
					<string>meta.link.inline.markdown</string>
				</dict>
			</array>
		</dict>
		<key>doctest</key>
		<dict>
			<key>begin</key>
			<string>(?:^|\G)\s*(iex(?:\(\d+\))?&gt;)(?=\s|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prompt.elixir</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A doctest continues on ...&gt; lines.</string>
			<key>contentName</key>
			<string>source.elixir</string>
			<key>name</key>
			<string>meta.embedded.doctest.elixir</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
			<key>while</key>
			<string>(?:^|\G)\s*(\.\.\.(?:\(\d+\))?&gt;)(?=\s|$)</string>
			<key>whileCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.prompt.elixir</string>
				</dict>
			</dict>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\(x[\da-fA-F]{1,2}|u\{[\da-fA-F]{1,6}\}|u[\da-fA-F]{4}|.)</string>
			<key>name</key>
			<string>constant.character.escaped.elixir</string>
		</dict>
		<key>function_parameters</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.function.elixir</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parameters may span lines and contain calls such as size(8) in binary patterns.</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function_parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>interpolated_elixir</key>
		<dict>
			<key>begin</key>
			<string>#\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.elixir</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.elixir</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.elixir</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.line.elixir</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nest_curly_and_self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>nest_curly_and_self</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.scope.elixir</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#nest_curly_and_self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>typespec</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>A named argument or element: reason :: term()</string>
					<key>match</key>
					<string>(?&lt;![.\w@:])(?!(?:_|nil|true|false)\b)[a-z_]\w*[?!]?(?=\s*::(?!:))</string>
					<key>name</key>
					<string>variable.parameter.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.optional.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.required.elixir</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(?:(optional)|(required))(?=\s*\()</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![.\w@:])(?:any|arity|as_boolean|atom|binary|bitstring|boolean|byte|char|charlist|float|fun|function|identifier|integer|iodata|iolist|keyword|list|map|maybe_improper_list|mfa|module|neg_integer|no_return|node|non_neg_integer|none|nonempty_binary|nonempty_bitstring|nonempty_charlist|nonempty_improper_list|nonempty_list|nonempty_maybe_improper_list|number|pid|port|pos_integer|reference|struct|term|timeout|tuple|var)\b(?![?!:])</string>
					<key>name</key>
					<string>support.type.elixir</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.elixir</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.elixir</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.language.elixir</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.method.elixir</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>storage.type.remote.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Remote types: String.t(), :inet.ip_address(), __MODULE__.t()</string>
					<key>match</key>
					<string>(?:\b([A-Z]\w*(?:\.[A-Z]\w*)*)|(:[a-z_]\w*)|\b(__MODULE__))\s*(\.)\s*([a-z_]\w*[?!]?)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![.\w@:])(?!(?:when|and|or|not|in|nil|true|false|do|end|fn|unquote)\b)(?!__\w+__\b|_\b)[a-z_]\w*[?!]?(?![?!:\w])</string>
					<key>name</key>
					<string>storage.type.custom.elixir</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.ellipsis.elixir</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.elixir</string>
	<key>uuid</key>
	<string>D00C06B9-71B2-4FEB-A0E3-37237F579456</string>
</dict>
</plist>
