<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Phoenix LiveView templates: HTML with {expressions}, components, and slots.</string>
	<key>fileTypes</key>
	<array>
		<string>heex</string>
	</array>
	<key>injections</key>
	<dict>
		<key>L:(text.html.heex meta.tag - meta.embedded.line.heex - string.quoted.double.html - string.quoted.single.html)</key>
		<dict>
			<key>comment</key>
			<string>{expressions} and :if/:for in HTML tags. HTML attribute strings are literal.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_attributes</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>name</key>
	<string>HEEx</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.elixir</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#components</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>comment</key>
			<string>Attributes of components and slots.</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_attributes</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic#entities</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s=/&gt;\"'{}]+</string>
					<key>name</key>
					<string>entity.other.attribute-name.heex</string>
				</dict>
			</array>
		</dict>
		<key>components</key>
		<dict>
			<key>comment</key>
			<string>Function components (&lt;.button&gt;, &lt;MyAppWeb.Components.card&gt;) and slots (&lt;:actions&gt;).</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(&lt;)(?:(\.)([a-z_]\w*[?!]?)|([A-Z]\w*(?:\.[A-Z]\w*)*)(\.)([a-z_]\w*[?!]?))(?=[\s/&gt;])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.method.heex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.component.heex</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.module.elixir</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.method.heex</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.component.heex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(/?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.component.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.method.heex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.component.heex</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.module.elixir</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.method.heex</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.component.heex</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;/)(?:(\.)([a-z_]\w*[?!]?)|([A-Z]\w*(?:\.[A-Z]\w*)*)(\.)([a-z_]\w*[?!]?))\s*(&gt;)</string>
					<key>name</key>
					<string>meta.tag.component.heex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&lt;)(:)([a-z_]\w*[?!]?)(?=[\s/&gt;])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.slot.heex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.slot.heex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(/?&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.tag.slot.heex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.begin.html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.slot.heex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.slot.heex</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.end.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;/)(:)([a-z_]\w*[?!]?)\s*(&gt;)</string>
					<key>name</key>
					<string>meta.tag.slot.heex</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.begin.heex</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.elixir</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.embedded.end.heex</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.embedded.line.heex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.elixir</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>HEEx ends the expression at the first unmatched }, even in a comment: {# note}</string>
					<key>match</key>
					<string>(#)[^}]*</string>
					<key>name</key>
					<string>comment.line.number-sign.elixir</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.elixir#nest_curly_and_self</string>
				</dict>
			</array>
		</dict>
		<key>special_attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.heex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;![\w:.-])(:(?:if|for))(?![\w:-])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.heex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;![\w:.-])(:(?:let|key|type))(?![\w:-])</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[^\s=])=(?=\s*\{)</string>
					<key>name</key>
					<string>punctuation.separator.key-value.html</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.heex</string>
	<key>uuid</key>
	<string>145BB046-3E39-4389-A775-97CDA3E8B7D3</string>
</dict>
</plist>
